name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (LTS)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova
        run: |
          npm install -g cordova@latest
          cordova telemetry off

      - name: Install dependencies
        run: npm install

      - name: Add Android platform
        run: |
          cordova platform add android@latest

      - name: Build APK (Release)
        run: |
          cordova build android --release -- --packageType=apk

      - name: Find APK file
        id: find-apk
        run: |
          APK_PATH=$(find platforms/android/app/build/outputs/apk -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: blackjack-wearos.apk
          path: ${{ steps.find-apk.outputs.APK_PATH }}
