name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Cordova and dependencies
        run: |
          npm install -g cordova@12.0.0
          npm install

      - name: Initialize Cordova project
        run: |
          cordova create . com.ferkusteam.blackjack.wear BlackJackWear
          cordova platform add android

      - name: Copy project files
        run: |
          cp -r www/* platforms/android/app/src/main/assets/www/
          cp config.xml platforms/android/

      - name: Build APK
        run: |
          cordova build android --release -- --packageType=apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: blackjack-wearos.apk
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
